spring.rabbitmq.addresses: ${RABBITMQ_HOSTS:127.0.0.1}
spring.rabbitmq.port: ${RABBITMQ_PORT:5672}
spring.rabbitmq.username: ${RABBIT_ADMIN:admin}
spring.rabbitmq.password: ${RABBIT_ADMIN_PASSWORD:admin}
spring.rabbitmq.requested-heartbeat: 10s
server.port: 8092
mcg.remoting:
   timeout: 4